#!/usr/bin/env bash
# Configures load balancer
apt-get update
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get update
apt-get install -y haproxy=2.0.*
service haproxy start
